/* This file is auto-generated by @finspotter/annotations. Do not edit. */

import * as bbox_xywh from "@finspotter/annotation-bbox_xywh/machine"
import * as bbox_xywha from "@finspotter/annotation-bbox_xywha/machine"
import * as segmentation from "@finspotter/annotation-segmentation/machine"
import * as bbox_xywha$segmentation from "@finspotter/annotation-bbox_xywha_segmentation/machine"

import { machine as nullMachine } from "./null/machine"

export const AnnotationTypes = [
  "bbox_xywh",
  "bbox_xywha",
  "segmentation",
  "bbox_xywha$segmentation",
] as const
export type AnnotationType = (typeof AnnotationTypes)[number]

export interface AnnotationDataTypes {
  bbox_xywh: [number, number, number, number]
  bbox_xywha: [number, number, number, number, number]
  segmentation: number[][]
  bbox_xywha$segmentation: { "bbox_xywha": [number, number, number, number, number]; "segmentation": number[][] }
}

export interface AnnotationDisplayTypes {
  bbox_xywh: { x: number; y: number }[]
  bbox_xywha: { x: number; y: number }[]
  segmentation: { x: number; y: number }[][]
  bbox_xywha$segmentation: { "bbox_xywha": { x: number; y: number }[]; "segmentation": { x: number; y: number }[][] }
}

const _machines = {
  bbox_xywh: bbox_xywh["machine"],
  bbox_xywha: bbox_xywha["machine"],
  segmentation: segmentation["machine"],
  bbox_xywha$segmentation: bbox_xywha$segmentation["machine"],
  null: nullMachine,
} as const

export type MachineType<T extends AnnotationType | "null"> =
  (typeof _machines)[T]
