import { writeFile } from "fs/promises"

export interface AnnotationPackage {
  pkg: string
  name: string
  dataType: string
  displayType: string
}

//TODO: format with prettier?
export function generateExports(mods: AnnotationPackage[]) {
  writeFile(
    "./packages/annotations/src/index.ts", //TODO: detect this location?
    generateAnnotationIndex(mods)
  )
  writeFile(
    "./packages/annotations/src/react/index.tsx", //TODO: detect this location?
    generateReactIndex(mods)
  )
}

function generateAnnotationIndex(mods: AnnotationPackage[]) {
  const imports = [
    `/* This file is auto-generated by @finspotter/annotations. Do not edit. */`,
    "",
    ...mods.map((mod) => `import * as ${mod.name} from "${mod.pkg}/machine"`),
    "",
    `import { machine as nullMachine } from "./null/machine"`,
    "",
  ]

  //TODO: export a name and description
  const typesAndInterfaces = [
    `export const AnnotationTypes = [`,
    ...mods.map((mod) => `  "${mod.name}",`),
    `] as const`,
    `export type AnnotationType = (typeof AnnotationTypes)[number]`,
    "",
    `export interface AnnotationDataTypes {`,
    ...mods.map((mod) => `  ${mod.name}: ${mod.dataType}`),
    `}`,
    "",
    `export interface AnnotationDisplayTypes {`,
    ...mods.map((mod) => `  ${mod.name}: ${mod.displayType}`),
    `}`,
    "",
  ]

  const machines = [
    `const _machines = {`,
    ...mods.map((mod) => `  ${mod.name}: ${mod.name}["machine"],`),
    `  null: nullMachine,`,
    `} as const`,
    "",
    `export type MachineType<T extends AnnotationType | "null"> =`,
    `  (typeof _machines)[T]`,
    "",
  ]

  return [...imports, ...typesAndInterfaces, ...machines].join("\n")
}

function generateReactIndex(mods: AnnotationPackage[]) {
  const imports = [
    `/* This file is auto-generated by @finspotter/annotations. Do not edit. */`,
    "",
    `import {`,
    `  ForwardRefExoticComponent,`,
    `  RefAttributes,`,
    `  SVGProps,`,
    `  type ComponentType,`,
    `  type PropsWithChildren,`,
    `} from "react"`,
    ...mods.map((mod) => `import * as ${mod.name} from "${mod.pkg}/react"`),
    `import {`,
    `  type AnnotationDataTypes,`,
    `  type AnnotationType,`,
    `} from "@finspotter/annotations"`,
    `import { type Transform } from "@finspotter/canvas"`,
    "",
    `import {`,
    `  type BaseAnnotationLayerProps,`,
    `  type ConvertTo,`,
    `} from "./BaseAnnotationLayer"`,
    `import { type BaseEditPanelProps } from "./BaseEditPanel"`,
    `import {`,
    `  type OptionalButton,`,
    `  type RequiredButtonProps,`,
    `} from "./EditPanelButton"`,
    `import * as nullAnnotation from "./NullAnnotation"`,
    "",
  ]

  const typeDefs = [
    `type AnnotationLayerProps<T extends AnnotationType | "null"> = Omit<`,
    `  BaseAnnotationLayerProps<T>,`,
    `  "strategy"`,
    `>`,
    ``,
    `type EditPanelProps<T extends AnnotationType | "null"> = PropsWithChildren<`,
    `  Omit<BaseEditPanelProps<T>, "strategy">`,
    `>`,
    ``,
    `type AnnotationModule<T extends AnnotationType | "null"> = {`,
    `  AnnotationLayer: ComponentType<AnnotationLayerProps<T>>`,
    `  EditPopover: ComponentType<object>`,
    `  EditPanel: ComponentType<EditPanelProps<T>>`,
    `  EditPanelButtons: RequiredButtonProps<T> & OptionalButton`,
    `  convertFrom?: ConvertTo<T>`,
    `  getTransformMatrix: (`,
    `    arg0: T extends AnnotationType ? AnnotationDataTypes[T] : null`,
    `  ) => Transform`,
    `  Icon?: ForwardRefExoticComponent<`,
    `    Omit<`,
    `      SVGProps<SVGSVGElement> & {`,
    `        title?: string`,
    `        titleId?: string`,
    `      },`,
    `      "ref"`,
    `    > &`,
    `      RefAttributes<SVGSVGElement>`,
    `  >`,
    `}`,
    "",
  ]

  const modulesObj = [
    `const modules: { [T in AnnotationType | "null"]: AnnotationModule<T> } = {`,
    ...mods.map((mod) => `  ${mod.name},`),
    `  null: nullAnnotation,`,
    `}`,
    "",
  ]

  const getAnnotationComponentsFn = [
    `export function getAnnotationComponents<T extends AnnotationType | "null">(`,
    `  type: T`,
    `): AnnotationModule<T> & {`,
    `  convertTo?: Partial<{`,
    `    [K in Exclude<AnnotationType | "null", T>]: ConvertTo<K>[T]`,
    `  }>`,
    `} {`,
    `  if (!modules[type])`,
    `    throw new Error(\`No module found for annotation type '\${type}'!\`)`,
    "",
    `  const module = modules[type] as AnnotationModule<T>`,
    `  // eslint-disable-next-line @typescript-eslint/no-explicit-any`,
    `  const convertTo: Record<string, ConvertTo<any>> = {}`,
    `  for (const [targetTypeStr, targetModule] of Object.entries(modules)) {`,
    `    if (targetTypeStr === type) continue`,
    `    const targetType = targetTypeStr as Exclude<AnnotationType | "null", T>`,
    `    if (`,
    `      targetModule?.convertFrom?.[`,
    `        type as keyof typeof targetModule.convertFrom`,
    `      ] !== undefined`,
    `    ) {`,
    `      convertTo[targetType] =`,
    `        targetModule!.convertFrom[type as keyof typeof targetModule.convertFrom]`,
    `    }`,
    `  }`,
    "",
    `  return {`,
    `    ...module,`,
    `    convertTo: Object.keys(convertTo).length`,
    `      ? (convertTo as Partial<{`,
    `          [K in Exclude<AnnotationType | "null", T>]: ConvertTo<K>[T]`,
    `        }>)`,
    `      : undefined,`,
    `  }`,
    `}`,
    "",
  ]

  return [
    ...imports,
    ...typeDefs,
    ...modulesObj,
    ...getAnnotationComponentsFn,
  ].join("\n")
}
