[project]
name = "finspotter"
version = "0.0.0"
requires-python = "==3.13.*"
dependencies = []

[tool.uv]
package = false

[tool.uv.workspace]
members = [
  "extensions/pipeline/*/detect",
  "extensions/pipeline/*/extract",
  "extensions/pipeline/*/pairwise",
  "extensions/pipeline/*/refine",
  "packages/pipeline/client",
]