/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "BETTER_AUTH_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Database": {
      "host": string
      "type": "sst.sst.Linkable"
    }
    "Email": {
      "from": number
      "noreply": number
      "smtp": {
        "auth": {
          "pass": number
          "user": number
        }
        "host": number
        "port": number
      }
      "type": "sst.sst.Linkable"
    }
    "UploadAssets": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "Web": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
  }
}

import "sst"
export {}