/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "AwsPoolProvider": {
      "name": string
      "project": string
      "type": "gcp.iam/workloadIdentityPoolProvider.WorkloadIdentityPoolProvider"
    }
    "BETTER_AUTH_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Database": {
      "host": string
      "type": "sst.sst.Linkable"
    }
    "Email": {
      "configSet": string
      "sender": string
      "type": "sst.aws.Email"
    }
    "SESSender": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SubmissionReviewPipeline": {
      "eventBus": string
      "identityPool": string
      "realtime": {
        "4dabf18193072939515e22adb298388d": string
        "id": string
        "packageVersion": string
        "urn": string
      }
      "table": string
      "type": "finspotter.pipeline.SubmissionReviewPipeline"
    }
    "SubmissionReviewPipelineSubmissions": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Uploads": {
      "name": string
      "type": "sst.sst.Linkable"
    }
    "Web": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
  }
}

import "sst"
export {}