/* This file is auto-generated by @finspotter/pipeline. Do not edit. */

import { type AnnotationType } from "@finspotter/annotations"

export const DetectionFunctions = [
  "yolact",
] as const
export type DetectionFunction = (typeof DetectionFunctions)[number]

interface DetectConfigs {
  yolact: {
    model: {
      bucket: string
      key: string
    }
    dataset: {
      class_names: string[]
      label_map: Record<number, number>
    }
    num_classes: number
    score_threshold: number
  }
}
export type DetectConfig<D extends DetectionFunction | undefined> =
  D extends DetectionFunction ? DetectConfigs[D] : never

export const ExtractionFunctions = [
  "hesaff",
] as const
export type ExtractionFunction = (typeof ExtractionFunctions)[number]

interface ExtractConfigs {
  hesaff: {
    numberOfScales?: number
    threshold?: number
    edgeEigenValueRatio?: number
    border?: number
    maxPyramidLevels?: number
    maxIterations?: number
    convergenceThreshold?: number
    smmWindowSize?: number
    mrSize?: number
    spatialBins?: number
    orientationBins?: number
    maxBinValue?: number
    initialSigma?: number
    patchSize?: number
    scale_min?: number
    scale_max?: number
    rotation_invariance?: boolean
    augment_orientation?: boolean
    ori_maxima_thresh?: number
    affine_invariance?: boolean
    only_count?: boolean
    use_dense?: boolean
    dense_stride?: number
    siftPower?: number
  }
}

export type ExtractConfig<E extends ExtractionFunction | undefined> =
  E extends ExtractionFunction ? ExtractConfigs[E] : never

export const SearchFunctions = [
  "faiss:pairwise",
  "pgvector:indexed",
] as const
export type SearchFunction = (typeof SearchFunctions)[number]

interface SearchConfigs {
  "faiss:pairwise": {
    index_string?: string
  }
  "pgvector:indexed": {}
}
export type SearchConfig<S extends SearchFunction | undefined> =
  S extends SearchFunction ? SearchConfigs[S] : never

export const MatchRefinementFunctions = [
  "ratio",
  "homog",
  "sum",
] as const
export type MatchRefinementFunction = (typeof MatchRefinementFunctions)[number]

interface RefineConfigs {
  ratio: {
    threshold?: number
  }
  homog: {
    ransacReprojThreshold?: number
  }
  sum: null
}

export type RefineConfig<R extends MatchRefinementFunction | undefined> =
  R extends MatchRefinementFunction ? RefineConfigs[R] : never

export const getAnnotationTypes: Record<string, AnnotationType> = {
  yolact: "segmentation",
}

export type AnnotationTypes = {
  yolact: "segmentation"
}
